#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	// Right Stick C - Left and Right  , D - Up and Down
	// Left Stick B - Left and right , A - UP and Down
	// tankControl ( Right, Left )
	// armControl  Motor,   Up , Down
	// Claw Motor   Moter , Up , Down
	repeat (forever) {
		//tankControl(ChD, ChA, 5);
		armControl(armMotor, BtnLUp, BtnLDown, 75);
		armControl(clawMotor, BtnRUp, BtnRDown, 15);

	}
}
